### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by certik** [awvwgk/toml-f#1]
@awvwgk, thanks for creating this package.

We are looking for a package to use as a TOML parser for the [Fortran Package Manager](
https://github.com/fortran-lang/fpm), see the issue for it at https://github.com/fortran-lang/fpm/issues/149.

It looks like your package would be exactly what we need. The only issue is that the `toml-f`'s GPL license would not allow us to distribute `fpm` under an MIT license as we currently do.

Would you be open to relicense `toml-f` to a more permissive license such as BSD, MIT or Apache?

If not, that is totally fine. I just wanted to ask.

**Comment by awvwgk** [comment]
Thanks for your interest, I actually have a strong preference for copyleft licenses. But I can see how this might become a general hurdle for reusing this project, probably a MIT/Apache-2 dual-licensing might work just fine.

Also, I should give this holiday project another look and get the TOML standard testsuite to pass than before it should be seriously considered for usage with `fpm`.

**Comment by certik** [comment]
Thanks for the reply @awvwgk. If you are open to dual license under MIT and GPL, I think that would work for us.

**Comment by certik** [comment]
Thank you @awvwgk, we really appreciate this!

**Comment by awvwgk** [comment]
@certik you're welcome.
